### PR TITLE
Update udf.md

### PR DESCRIPTION
**Pull request by kghamilton89**

### CODE REVIEW

**Comment by rodionos** [comment]
Ken, does your PR take into account changes in https://github.com/axibase/charts/pull/5? Thanks.

**Comment by kghamilton89** [comment]
I believe so, I just checked my email this morning and saw that you wanted
a new review. I started to review the most current document this morning.
Is that what you're asking?

вт, 26 сент. 2017 г. в 18:14, Sergei Rodionov <notifications@github.com>:

**Comment by rodionos** [comment]
Please review changes in the PR 5: https://github.com/axibase/charts/pull/5
That's the link I included in the email. This PR has multiple files not just udfs, which is how I noticed that something is missing.

**Comment by rodionos** [comment]
The current document is ok 'as is'.

**Pull request closed without merging**
