### PR TITLE
property-table

### PR DESCRIPTION
**Pull request by kghamilton89**
## Property Table

* **Format-only** refactoring of Property Table Settings documentation.

### CODE REVIEW

**Comment by rodionos** [comment]
The issue I noticed is that some settings are lost and/or misnamed compared to the original document. Example:

image

image

Another example. The original document has setting 'exact-match', the proposed document has setting `exactMatch`. By original document I mean: https://axibase.com/products/axibase-time-series-database/visualization/widgets/property-table-widget/

---

As a result, I cannot accept other PRs due to the risk of information loss. By which I mean, what if new PRs lose or rename settings?

Please go back to original [documentation](https://axibase.com/products/axibase-time-series-database/visualization/widgets/) and review ALL pending PRs for charts to locate missing or incorrectly names settings. By review I mean a careful, line-by-line review to eliminate information loss and to retain correct setting names.

**Comment by kghamilton89** [comment]
Chats allows settings to be written as `time-span` or `timespan`, `exact-match` or `exactmatch`. Would you like to eliminate the hyphen here as well?

**Comment by rodionos** [comment]
In most cases, we need hyphen to separate words, but `timespan` is a single word. So `exact-match` and `timespan`.

**Comment by kghamilton89** [comment]
There are very few content changes to this document. I've run all the examples through the plugin and compared the document to the source. Mostly the content changes involve adding phrasing like "Possible values: `false`, `true`" or removing verbs which do not add to the content of the descriptions.

**Comment by rodionos** [comment]
1) Lead example:

```
[configuration]
  height-units = 2
  width-units = 1

[group]
[widget]
	type = property
	title = System Properties
    expand-tags = true
    timespan = all
	transpose = true
      
	[property]
		type = configuration
		entity = nurswgvml007
```

2) Some settings from `[column]` sections are implemented exactly as in shared table and therefore can be omitted. For example, `format`, but perhaps other - review one by one. If descriptions are largely the same, the setting listed in shared document, can be omitted in specific document.

3) There is no such setting: `key-tag-manager`, but I think I already alerted you on this. There is `key-tag-expression` which provides an example where it's listed. Because of issue with `key-tag-manager` it seems that this widget would benefit from manual review of all settings one by one to avoid problems such as with this setting. Reference page: https://axibase.com/products/axibase-time-series-database/visualization/widgets/property-table-widget/

**Comment by kghamilton89** [comment]
1. Refactored lead chart.
2. Removed `format` setting from `[column]` settings as requested as well as `tag`, and `value` which are also defined there.
3. This is a thoughtless error, I've just moved it around so many times that when I did it most recently I guess the incorrect name was stuck in my head for some reason.

**Pull request merged**
