### PR TITLE
Fixed start/end-time description

### PR DESCRIPTION
**Pull request by annstriganova**

### CODE REVIEW

**Comment by rodionos** [comment]
@annstriganova - do the end-time and timespan settings work as proposed when start-time is set in the future, for example, `next_day`?

**Comment by annstriganova** [comment]
Yes.
Selection_002
The same for `end-time = next_day`:
Selection_003

**Comment by rodionos** [comment]
Is the default 1 hour timespan the same for all widget types, e.g. console, property?

**Comment by annstriganova** [comment]
All, except `console`, there is `timespan = all` for this widget.

**Pull request merged**
