### PR TITLE
Fix mapping path in UDF

### PR DESCRIPTION
**Pull request by kirmanak**
I doubt that `/portal/resource/` can be mapped to `/opt/atsd/atsd/conf/portal/scripts/`, it is non-logical. I tested on my local ATSD,  file `/opt/atsd/atsd/conf/portal/scripts/fred.js` can be accessed via `https://localhost:8443/portal/resource/scripts/fred.js`, but not `https://localhost:8443/portal/resource/fred.js`

### CODE REVIEW

**Comment by rodionos** [comment]
Please test if what we're describing is correct by placing files to /opt/atsd/atsd/conf/portal and trying different relative paths.

**Comment by rodionos** [comment]
Need a table with import setting value, url path, fs location for various settings: name, relative with slash, absolute with slash, full url including protocol and host.

**Comment by kirmanak** [comment]
@rodionos Added the table, but I finished before saw your note. What should I change?

**Comment by kirmanak** [comment]
@rodionos I believe use `import fred = resource/path/fred.js` and `import fred = /portal/resource/path/fred.js` is better, because different paths aren't mapped anywhere.

**Comment by rodionos** [comment]
@kirmanak - please keep my examples, add yours as extra rows. Verify that each example works.

**Pull request merged**
