### PR TITLE
treemap-settings

### PR DESCRIPTION
**Pull request by kghamilton89**
Refactor of Treemap Widget settings.

### CODE REVIEW

**Comment by kghamilton89** [comment]
* This PR is all but complete, all setting have been verified against the original documentation, all examples have been run through the plugin.
* Waiting for confirmation on the functionality of `gradient-count` setting.

**Comment by rodionos** [comment]
Colors and thresholds are incorrectly documented: https://apps.axibase.com/chartlab/1fe8d669/2/

**Comment by kghamilton89** [comment]
I modified `colors`, `color-range`, and `thresholds` to include their relationship.

**Comment by kghamilton89** [comment]
Table has been refactored to remove the `Example` column and integrate its contents into the `Description` column.

**Comment by rodionos** [comment]
1) colors and thresholds should be in one table
2) lead example should include defined thresholds and colors
3) use comparable metrics / different metrics for showcasing thresholds and color assignment - to compare apples and apples.
4) items inside the `mode` cell are better placed on separate lines.
5) `sector` is a circle part (which is why I used it gauge). In case of treemap, I think `rectangle` or `area` is more appropriate. 
6) I don't see from the provided example, that `gradient-count` has any effect. Is this setting documented as support in axibase.com docs?

**Comment by rodionos** [comment]
Because of `gradient-count` presence, check which settings are new (not present in axibase.com) and which settings have been ignored. Double check which settings have effect taking into account their description. Sometimes you need to use different series to observe impact.

**Comment by kghamilton89** [comment]
With respect to `gradient-count`, it is supported according to source documentation, in order to see its effects in the examples see the upper-right corner where the gradient count is expanded for each threshold area:

image

I'll update the image to show the effect more obviously.

**Comment by kghamilton89** [comment]
With respect to `gradient-count`, it is supported according to source documentation, in order to see its effects in the examples see the upper-right corner where the gradient count is expanded for each threshold area:

image

It does generally behave pretty strangely.

* No effect if `color-range` is not set to more than one color: https://apps.axibase.com/chartlab/d3f3c8b4
* No effect if `colors` is used instead of `color-range` w/ multiple colors: https://apps.axibase.com/chartlab/6f857270

To see effect, user must use `color-range = {multiple-colors}`

I'll update the image to show the effect more obviously.

**Comment by kghamilton89** [comment]
With respect to `gradient-count`, it is supported according to source documentation, in order to see its effects in the examples see the upper-right corner where the gradient count is expanded for each threshold area:

image

It does generally behave pretty strangely.

* No effect if `color-range` is not set to more than one color: https://apps.axibase.com/chartlab/d3f3c8b4
* No effect if `colors` is used instead of `color-range` w/ multiple colors: https://apps.axibase.com/chartlab/6f857270

To see effect, user must use `color-range = {multiple-colors}`

I'll update the image to show the effect more obviously.

**Comment by kghamilton89** [comment]
With respect to `gradient-count`, it is supported according to source documentation, in order to see its effects in the examples see the upper-right corner where the gradient count is expanded for each threshold area:

image

It does generally behave pretty strangely.

* No effect if `color-range` is not set to more than one color: https://apps.axibase.com/chartlab/d3f3c8b4
* No effect if `colors` is used instead of `color-range` w/ multiple colors: https://apps.axibase.com/chartlab/6f857270

To see effect, user must use `color-range = {multiple-colors}`

I'll update the image to show the effect more obviously: https://apps.axibase.com/chartlab/c1ee249b

**Comment by kghamilton89** [comment]
With respect to `gradient-count` setting:

* To observe effects, see the color legend in the upper right corner.
  * `gradient-count = 2`
  image  
  * `gradient-count = 4`
  image
* There are some quirks to the setting though: 
  * `color-range` must be defined with **multiple** colors. Specifying `color-range = red` for example creates a chart where `gradient-count` has no effect: https://apps.axibase.com/chartlab/ffcf3fb2
  * Likewise, defining `colors` with multiple colors has no effect: https://apps.axibase.com/chartlab/4e8a3db9

I'll update the example chart to more clearly demonstrate the effects of the `gradient-count`: https://apps.axibase.com/chartlab/c1ee249b

**Comment by kghamilton89** [comment]
With respect to `gradient-count` setting:

* To observe effects, see the color legend in the upper right corner.
  * `gradient-count = 2`
  image  
  * `gradient-count = 4`
  image
* There are some quirks to the setting though: 
  * `color-range` must be defined with **multiple** colors. Specifying `color-range = red` for example creates a chart where `gradient-count` has no effect: https://apps.axibase.com/chartlab/ffcf3fb2
  * Likewise, defining `colors` with multiple colors has no effect: https://apps.axibase.com/chartlab/4e8a3db9

I'll update the example chart to more clearly demonstrate the effects of the `gradient-count`: https://apps.axibase.com/chartlab/c1ee249b

**Pull request merged**
