### PR TITLE
Functions

### PR DESCRIPTION
**Pull request by YanaNik**
I've added description of all functions in one file. In Overview section there is brief description, list of arguments and type of return value. Further the expanded description with ChartLab examples and arguments info is placed.

### CODE REVIEW

**Comment by rodionos** [comment]
Lets trim the summary table by keeping only function name and a brief description. Arguments, scope, etc are covered in the function section. The description should be brief. A more detailed description can be placed into the function section

**Comment by rodionos** [comment]
@kghamilton89 Ken, is it clear for you as a user - what each function does?

**Comment by kghamilton89** [comment]
Yes, it's well written and I tried to maintain the "template" style that Yana used from the start. I'm reviewing it again now to be sure because it's a large document.

**Comment by kghamilton89** [comment]
I believe it is a comprehensible document, and the template style helps when new functions are introduced. For example, the getTags() and requestEntitiesMetricsValues() sections are written similarly making them pretty easy to compare to one another. getTags() is a standard function that is featured in other db's, while requestEntitiesMetricsValues() is not, so it helps that it is written with familiar language. Is there a specific function you think is ambiguously worded?

**Comment by rodionos** [comment]
@kghamilton89 Ken, pls review the latest changes/version

**Comment by YanaNik** [comment]
@kghamilton89
I've rewritten the descriptions in "Overview" table, so descriptions are small. In expanded descriptions I changed "Description" section and added "Syntax", "Scope of usage" and "API Request". Other sections not changed.

**Comment by kghamilton89** [comment]
I think the whole document is much more readable with the new presentation.

**Pull request merged**
