### PR TITLE
alert-console-table-reformat

### PR DESCRIPTION
**Pull request by kghamilton89**
* Just a refactoring of the format of the already-merged Alert Console docs to remove the `Example` column.
* I added the Possible Values section which we began using after this was originally made, and updated all the examples so they work with the plugin (latest version). The only plugin error is that it believes that Alert Console required `[series]` level setting when it does not: https://github.com/axibase/axibase-charts-vscode/issues/197
* I did modify the content of the `sort` setting, but I used the content from an [already merged section](https://github.com/axibase/charts/blob/master/widgets/bar-chart/README.md#sort), and applied it to this widget.

### CODE REVIEW

**Comment by rodionos** [comment]
1) https://apps.axibase.com/chartlab/1735445f/2/

The lead example is too limited I think ( no settings):

```
[widget]
  title = Entity alerts
  type = console
  entity = nurswghbs001
```

2) Split all settings that deal with data loading and filtering into a separate table `Data Loading`.

**Comment by rodionos** [comment]
I accidentally closed the PR. Re-opening.

**Comment by rodionos** [comment]
See changes required above: https://github.com/axibase/charts/pull/108#issuecomment-429856126

**Comment by kghamilton89** [comment]
1. My logic was that typically we try to show the *most* limited working configuration, but I agree that it seems too limited. I thought the same thing when I made it but I wanted to stay consistent.

2. **Data Loading** table created.

3. I removed the `severity-style = row` example from the Examples section since it's the default setting.

4. I resized other images to at least fit their vertical height in the shot, unless the image would have just been massive otherwise.

**Pull request merged**
